[build]
  publish = "/"

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/music/*"
  to = "/music/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"
    Cache-Control = "public, max-age=0, must-revalidate"

[dev]
  framework = "#static"
